### ISSUE TITLE
POC - build stenciljs components

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#1757] opened 2020-10-08 13:13 UTC
The idea of this POC:
- build 2-3 stencils components using fundamental styles and https://stenciljs.com/
- build a small app using the components from previous point
- summarize the experience of building/consuming components (write like a blog), analyze the blueprint, performance, theming, features

Time box: 3 days

**Comment by InnaAtanasova** [comment] 2020-10-23 19:12
We build 3 components using StencilJs - button, select and avatar. Some of the issues we faced are discussed in the readme file of the demo app. Next step would be to use these components inside an Angular app and see how they would work there. For this, another ticket will be created and the work will be done in the next sprint. The issue is closed as done.

**Closed by InnaAtanasova** 2020-10-23 19:12 UTC
Labels: denoland
