### ISSUE TITLE
bug(styles): form grid

### ISSUE THREAD

**Issue by platon-rov** [SAP/fundamental-styles#3574] opened 2022-06-13 10:11 UTC
### Description

We have incorrect margins and paddings in the forms because in the `form-grid` we're relying on the classes from the `layout-grid`. As they may be nested very specifically we cannot cover them correctly. 

<img width="501" alt="image" src="https://user-images.githubusercontent.com/20265336/173329340-3458722f-8e67-4db3-b10f-a8a5fe81ae24.png">

Currently we have several independent components to manage form layouts

* form-item
* form-group
* form-grid

Although they can be independently used we should apply margins & paddings to them when they're used together. 
Proposed structure:

```
fd-container fd-form-layout-grid (main form wrapper, nothing changed)
	fd-row 
		fd-col fd-form-header
			Form Header
	fd-row fd-form-group (has 1rem paddings, one or more in each form)
		fd-col
			fd-form-group-header
				Form Group Header
			fd-row fd-form-item (one or more in each group, every item from 2nd in group has margin-top in vertical mode)
				fd-col fd-col--sm-4
					fd-form-label
						Form Label
				fd-col fd-col--sm-8
					fd-input
						Input
			fd-row fd-form-item (has 0.625rem margin on xs devices because from shown in vertical mode there)
				fd-col-4 fd-col--sm-4
					fd-form-label
						Form Label
				fd-col-8 fd-col--sm-8
					fd-input
						Input
```

### Cons

* Breaking Changes to be introduced, `fd-form-group` & `fd-form-item` classes applying to be needed.

**Comment by InnaAtanasova** [comment] 2022-08-10 19:50
A few things worth mentioning (in my opinion):
1. The spacing between the elements (horizontal and vertical layout) is achieved by adding margins. Nothing wrong with this approach, but it will 1) require to remove the margin from the first child element and 2) in the next screenshot you will see that it's actually deviating from the specs. The spacing can be achieved by using `gap` property of flex and set it to the value based on the screen size.
<img width="607" alt="Screen Shot 2022-08-10 at 3 41 10 PM" src="https://user-images.githubusercontent.com/39598672/184005975-912de892-3007-41af-bce0-05bdaea3d5f6.png">

2. The way we have it now each element gets a horizontal margin of 0.25rem, which combined with the adjacent element forms a gap of a 0.5rem, as specified in the specs. The problem is that on the side that is not adjacent to another element you now have an extra 0.25rem margin, as you can see in the following sscreenshots:
<img width="779" alt="Screen Shot 2022-08-10 at 3 46 21 PM" src="https://user-images.githubusercontent.com/39598672/184006575-745d336c-fed2-4e53-9a32-bffd509b9af8.png">
<img width="658" alt="Screen Shot 2022-08-10 at 3 46 07 PM" src="https://user-images.githubusercontent.com/39598672/184006578-d90e8212-db19-4689-bc72-638080c039ee.png">

 
Here's how it's in the specs:
<img width="652" alt="Screen Shot 2022-08-10 at 3 42 05 PM" src="https://user-images.githubusercontent.com/39598672/184006982-3c23d1af-6f92-47ed-8d61-ba8fc69b733e.png">

The `gap` marked as `E` and the gap `G` in the specs are only applied between elements. 
This again can be avoided with flex gap.

**Closed** 2022-08-15 08:50 UTC
Labels: Bug
