### ISSUE TITLE
'HCW and HCB' theme for Emphasised button border are not matching with fiori3

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#1296] opened 2020-07-27 16:30 UTC
**Describe the bug**
Emphasized button styles are deviating from HCB and HCW values of fiori3.

> Is this issue related to a specific component?
Button, menu button, split menu, button with icon

> What version of the Fundamental Library Styles are you using?
0.11

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**To Reproduce**
1. change the background to HCB or HCW.

<img width="355" alt="Screen Shot 2020-07-27 at 9 45 34 PM" src="https://user-images.githubusercontent.com/53487468/88567025-88d96400-d054-11ea-8d34-3b36bb48fd8a.png">

<img width="579" alt="Screen Shot 2020-07-27 at 9 24 54 PM" src="https://user-images.githubusercontent.com/53487468/88566844-3ef07e00-d054-11ea-93da-63202d23ed53.png">

**Expected behavior**
button styles should match as per fiori3.

<img width="870" alt="Screen Shot 2020-07-27 at 9 25 57 PM" src="https://user-images.githubusercontent.com/53487468/88567046-91319f00-d054-11ea-8dd1-8c30c050f709.png">

**Comment by salarenko** [comment] 2020-07-28 08:06
Duplicate of #1028

**Closed by salarenko** 2020-07-28 08:06 UTC
