### ISSUE TITLE
Avatar - wrong position of the zoom icon

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#2513] opened 2021-06-30 02:17 UTC
Avatar - wrong position of the zoom icon
<img width="1236" alt="Screen Shot 2021-03-25 at 4 36 39 PM" src="https://user-images.githubusercontent.com/39598672/112540277-5d944980-8d88-11eb-9442-35592c18684b.png">

**Comment by N1XUS** [comment] 2021-07-06 10:57
Duplicate of #2111

**Closed by N1XUS** 2021-07-06 10:57 UTC
Labels: Bug, denoland-porto
