### ISSUE TITLE
checkbox tristate issue

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#2515] opened 2021-06-30 02:18 UTC
TriState alignment of Checkbox - TBD
<img width="392" alt="Screen Shot 2021-03-25 at 4 41 26 PM" src="https://user-images.githubusercontent.com/39598672/112540829-0773d600-8d89-11eb-94cf-eb7260f7b40d.png">

**Comment by N1XUS** [comment] 2021-07-06 10:58
Duplicate of #2152

**Closed by N1XUS** 2021-07-06 10:58 UTC
Labels: Bug, denoland-porto
