### ISSUE TITLE
Pagination: Color issue with the arrow for left and right, and dots between the pages

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-styles#1859] opened 2020-11-05 19:55 UTC
Style issue: Color

**Describe the bug**
-If you are on the first or last page, the arrow for left or right should be grey, not ghost blue
-Dots between pages should be blue, not grey
Example: 
![Screen Shot 2020-11-05 at 11 53 59 AM](https://user-images.githubusercontent.com/72403541/98289901-87073100-1fb1-11eb-92c0-5ff8538a187f.png)
![Screen Shot 2020-11-05 at 11 54 07 AM](https://user-images.githubusercontent.com/72403541/98289905-879fc780-1fb1-11eb-9b90-ccefaf57934e.png)

**Comment by itmilos** [comment] 2021-03-09 12:46
This is a duplicate of https://github.com/SAP/fundamental-styles/issues/1860

**Comment by InnaAtanasova** [comment] 2021-03-09 15:05
closing in favour of #1860

**Closed by InnaAtanasova** 2021-03-09 15:05 UTC
Labels: Duplicate, denoland, winter 2020
