### ISSUE TITLE
Defect Hunting Fundamental Styles 0.12

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#1432] opened 2020-08-25 23:20 UTC
Test the library and the doc website. Log issues

**Comment by puru-hk** [comment] 2020-09-04 11:51
Below example is missing in Object Marker styles.

![image](https://user-images.githubusercontent.com/32538291/92236421-048bc380-eed3-11ea-937b-21688a00c946.png)

**Comment by manjunathanagaraj** [comment] 2020-09-08 06:29
@puru-hk , could you please check on Fiori3 visual specs version? I think we should be refering to Fiori3 styles, not Fiori2.

**Comment by Lokanathan-k** [comment] 2020-09-08 07:51
@puru-hk the above examples has been implemented please find the screen shots below.
pls use this staging url to cross verify

https://deploy-preview-1194--fundamental-styles.netlify.app/?path=/docs/components-object-marker--icon-only

<img width="1676" alt="Screenshot 2020-09-08 at 1 16 36 PM" src="https://user-images.githubusercontent.com/53534379/92448319-0ce74580-f1d6-11ea-88c9-9bb97a63b4bd.png">

**Comment by manjunathanagaraj** [comment] 2020-09-08 15:12
As per comments, its not a bug and closing it. There are sufficient examples.

**Closed by manjunathanagaraj** 2020-09-08 15:12 UTC
Labels: 0.12.0, Defect Hunting
